site_name: ASPECT-ui documentation
pages:
- home: index.md
- user interface: aspectui.md
- features to come: wishlist.md
- applications: applications.md
- 'hidden': 'applications/QSO_clustering_redshift_mapping.md'
- related tools: related_tools.md
- contact: contact.md
theme: readthedocs
theme_dir: 'theme_customization'
